name: Nano Code

on: 
  workflow_dispatch:
    inputs:
    task:
    description: 'Nano Codeに実行させるタスク'
    required: false
    default: 'これはテストです'

permissions: {}


jobs:
  nano-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Git ユーザーを設定
        run: |
          git config user.name "nano-code[bot]"
          git config user.email "nano-code[bot]@users.noreply.github.com"
      - name: Nano Codeを実行
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_PROVIDER: ${{ vars.LLM_PROVIDER }}
          LLM_MODEL: ${{ vars.LLM_MODEL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          ISSUE_BODY: ${{ inputs.task }}
        run: bun run agent --yolo